config/routes.rb
Prueba1::Application.routes.draw do
  resources :personas

end

app/models/persona.rb
class Persona < ActiveRecord::Base
  validates_presence_of :nombre,:apellido,:bio
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  # GET /personas
  # GET /personas.xml
  def index
    @personas = Persona.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @personas }
    end
  end

  # GET /personas/1
  # GET /personas/1.xml
  def show
    @persona = Persona.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @persona }
    end
  end

  # GET /personas/new
  # GET /personas/new.xml
  def new
    @persona = Persona.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @persona }
    end
  end

  # GET /personas/1/edit
  def edit
    @persona = Persona.find(params[:id])
  end

  # POST /personas
  # POST /personas.xml
  def create
    @persona = Persona.new(params[:persona])

    respond_to do |format|
      if @persona.save
        format.html { redirect_to(@persona, :notice => 'Persona was successfully created.') }
        format.xml  { render :xml => @persona, :status => :created, :location => @persona }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @persona.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /personas/1
  # PUT /personas/1.xml
  def update
    @persona = Persona.find(params[:id])

    respond_to do |format|
      if @persona.update_attributes(params[:persona])
        format.html { redirect_to(@persona, :notice => 'Persona was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @persona.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1
  # DELETE /personas/1.xml
  def destroy
    @persona = Persona.find(params[:id])
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to(personas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba1</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personas/_form.html.erb
<%= form_for(@persona) do |f| %>
  <% if @persona.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
      <% @persona.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br />
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :activo %><br />
    <%= f.check_box :activo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render 'form' %>

<%= link_to 'Show', @persona %> |
<%= link_to 'Back', personas_path %>

app/views/personas/index.html.erb
<h1>Listado de Personas</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Bio</th>
    <th>Activo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @personas.each do |persona| %>
  <tr>
    <td><%= persona.nombre %></td>
    <td><%= persona.apellido %></td>
    <td><%= persona.bio %></td>
    <td><%= persona.activo %></td>
    <td><%= link_to 'Show', persona %></td>
    <td><%= link_to 'Edit', edit_persona_path(persona) %></td>
    <td><%= link_to 'Destroy', persona, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Persona', new_persona_path %>

app/views/personas/new.html.erb
<h1>Nueva Persona (cambio urgente)</h1>

<%= render 'form' %>

<%= link_to 'Back', personas_path %>

app/views/personas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @persona.nombre %>
</p>

<p>
  <b>Apellido:</b>
  <%= @persona.apellido %>
</p>

<p>
  <b>Bio:</b>
  <%= @persona.bio %>
</p>

<p>
  <b>Activo:</b>
  <%= @persona.activo %>
</p>


<%= link_to 'Edit', edit_persona_path(@persona) %> |
<%= link_to 'Back', personas_path %>